### ISSUE TITLE
Only the first song is being shown

### ISSUE THREAD

**Issue by Yoposoc** [Sorashi/DiscordNowPlayingSong#1]
Unless I'm dumb, this isn't working. It appears the console is working as intended:
http://qr.net/bUymp

But my "Playing____" message on discord is not changing as intended. The console does say that I am logged into discord.

**Comment by AlexFDR** [comment]
same here, i can find the "game" with the song name but it doesn't sync with spotify and it's always the first music i was playing when i chose the "game" with the song's name.

**Comment by Sorashi** [comment]
I ran into this bug only once, the next time I debugged it weren't there, so that's why I let it through. The first reason that comes to my mind is the necessary multi-threading when using DiscordSharp. I'll look into it in a few days.

Sorry for the late response, I was on my vacation.

**Comment by Sorashi** [comment]
The bug keeps happening at some times. If you get this bug, simply restart the app.
It will be fixed with the rewrite for [Discord.Net](https://github.com/RogueException/Discord.Net), which is coming in the next few days.

**Comment by AlexFDR** [comment]
i trust this will work but i'll leave a message confirming it does once discord fixes the connection issues.

**Comment by AlexFDR** [comment]
https://gyazo.com/8b7527e12db8408e6aee221e635e81e1

still doesn't work even when restarting the app (also it seems the app only works if you run it as an admin now, just worth to point out). no other ideas apart from waiting for discord.net's update?

also, while i'm at it, ill leave a suggestion, show the name of the band as well.

**Comment by Sorashi** [comment]
@AlexFDR try using the [web version of Spotify](https://play.spotify.com) with [Last.fm scrobbler](https://chrome.google.com/webstore/detail/hhinaapppaileiechjoiifaancjggfjm) for Chrome

**Comment by Yoposoc** [comment]
@Sorashi I have downloaded the new version and tried it out as an administrator. It still does not work at all for me. Not sure why.
One thing I have done is pick an arbitrary program as my "Now Playing" program and renamed it, like so: https://a.uguu.se/p1TIwZBibZsR_Discord_2016-07-31_14-51-35.png
Not sure if that makes a difference.

**Comment by AlexFDR** [comment]
@Sorashi , on spotify web i cant even find the song on the games tab
https://gyazo.com/b3043ef049abaa65692e0a83bda172d0

just to make sure, you have to find a game with the %songname% - %Musicname% right?
(or in my case only the %songname%)
https://gyazo.com/7cd02c78d5bbc7581675dd4e8cf963da

**Comment by AlexFDR** [comment]
I feel like i should be either calling my self an idiot or patting myself in the back for thinking of this.
https://gyazo.com/d6d8e70db972b741ebf58c1bf44b5b7b

apparently the app worked all along but the thing is it doesn't show on my app or account
i opened the browser with a random account and it was working. weird

**Comment by Yoposoc** [comment]
It seems like it is indeed the same case with me:
Looking with another account: http://qr.net/bVhr5
Looking with my own account: http://qr.net/bVhr5 (didn't change).
Really strange.

**Comment by Sorashi** [comment]
Join the [Discord server](https://discord.gg/fDXXqk3) if you are interested in futher discussion.
I'm working on the rewrite for another API implementation, which should be more convinient in terms of reliability.

**Comment by Sorashi** [comment]
@Yoposoc @AlexFDR 

So this project is going to end, because the [terms of usage](https://discordapp.com/tos#rules-of-conduct-and-usage) of Discord, claim that it's forbidden to

> attempt to obtain passwords or other private information from other members;

Even though I'm not obtaining the credentials myself, the app explicitly requires them.

If you really want this features are heard rumors about Discord adding some kind of addon store. If this happens, I will immediately start working on it.

Bye for now.

**Comment by AlexFDR** [comment]
@Sorashi shame, its a really nice feature that should be in the software by default, either way, we can still use this as it is so its not really a big problem. ty for your work.

**Comment by Yoposoc** [comment]
@Sorashi Damn shame. It's a consented access by the user, so seems a bit strange for Discord to disallow that. Oh well, rules are rules. I can understand why you will stop development. Like @AlexFDR said, I'll just keep using it for now as long as it works. Thanks.

**Comment by Sorashi** [comment]
@AlexFDR @Yoposoc

Lol, good news guys, I spoke with a Discord dev and he told me that the statement is about stealing accounts.

Next good news - I made a web version of the app. You just open [this site](http://kazarp.website.tk/discordnowplayingsong/) in your browser, fill in the info and keep it open. That's it. You can run it from anywhere you want. Even from your mobile phone browser! Lol

**Comment by AlexFDR** [comment]
@Sorashi wasn't sure that i was going to use the browser version but that's nice considering the app takes up a lot of resources concerning CPU. any chance of "fixing" that? also, i found that if i close the app discord keeps playing the last song i listened to until i restart it. any way to make it so if the app is closed, it stops playing?
